### ISSUE TITLE
Unexpected behaviour in admin UI if change permission is set to False

### ISSUE THREAD

**Issue by barsch** [feincms/feincms3#40]
I would expected that if I set a Page object to not modifiable that the sidebar is not shown at all. Additionally a unexpected red tab with "Unknown region: undefined" appears and the delete checkbox is replaced with a drop down menu:

![Bildschirmfoto am 2024-05-02 um 01 58 56](https://github.com/feincms/feincms3/assets/602450/6cefdc85-d516-43f3-a7fd-4cbfdf7ac17a)

### Pseudo code
models.py
```python
class Page(AbstractPage, RedirectMixin):
    regions = [
        Region(key="main", title="Main"),
    ]
    ...
```

admin.py
```python
@admin.register(models.Page)
class PageAdmin(ContentEditor, TreeAdmin):
    inlines = [
        RichTextPluginInline,
        ImageWithRichTextPluginInline,
        PeoplePluginInline,
    ]
    ...

    def has_change_permission(self, request, obj=None):
        return False

    def has_delete_permission(self, request, obj=None):
        return False
```

**Comment by barsch** [comment]
Thank you for the quick fix!

If not to troublesome I would suggest to also hide the following elements: 

![Screenshot 2024-05-02 at 15-21-06 View page EGU site administration](https://github.com/feincms/feincms3/assets/602450/ead7fe8d-6365-4214-8b47-b3ae29a4c06e)

**Comment by matthiask** [comment]
Makes sense!

**Comment by barsch** [comment]
looking good - thank you again for the very quick fix!

NB: one could still use drag & drop plugins - but that is not very obvious - nothing happens anyway
